name: macOS CI

on:
  push:
    branches: [ "actions" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: brew install sdl2
    - name: Build PSXE
      run: make
    - name: Pack executable
      run: |
           chmod 755 bin/psxe
           mkdir -p psxe.app/Contents/MacOS
           mv bin/psxe psxe.app/Contents/MacOS
           mv .github/workflows/macOS/Libraries psxe.app/Contents/
           mv .github/workflows/macOS/Info.plist psxe.app/Contents/Info.plist
           mkdir -p psxe
           mv psxe.app psxe
    - uses: actions/upload-artifact@v3
      with:
        name: psxe
        path: psxe/