name: macOS CI

on:
  push:
    branches: [ "actions" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: brew install sdl2
    - name: Build PSXE
      run: make
    - name: Prepare libraries
      run: lipo -create
           .github/workflows/macOS/Libraries/arm64/libSDL2-2.0.0.dylib
           .github/workflows/macOS/Libraries/x86_64/libSDL2-2.0.0.dylib
           -o libSDL2-2.0.0.dylib
    - name: Pack executable
      run: |
           brew install dylibbundler