name: macOS CI

on:
  push:
    branches: [ "actions" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: brew install sdl2
    - name: make
      run: make
    - name: Pack executable
      run: |
           chmod 755 bin/psxe
           mkdir -p psxe.app/Contents/MacOS
           mkdir -p psxe.app/Contents/Libraries
           mv bin/psxe psxe.app/Contents/MacOS
           mv .github/workflows/macOS/ psxe.app/Contents/MacOS/
           zip -r psxe.zip psxe.app
    - uses: actions/upload-artifact@v3
      with:
        name: binary
        path: psxe.zip