name: macOS CI

on:
  push:
    branches: [ "actions" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: brew install sdl2
    - name: Build PSXE
      run: make
    - name: Prepare libraries
      run: lipo -create
           .github/workflows/macOS/Libraries/arm64/libSDL2-2.0.0.dylib
           .github/workflows/macOS/Libraries/x86_64/libSDL2-2.0.0.dylib
           -o libSDL2-2.0.0.dylib
    - name: Pack executable
      run: |
           brew install dylibbundler
           mkdir -p psxe.app/Contents/MacOS/libs
           mv bin/psxe psxe.app/Contents/MacOS
           chmod 755 psxe.app/Contents/MacOS/psxe
           dylibbundler -b -x ./psxe.app/Contents/MacOS/psxe -d ./psxe.app/Contents/libs/
           mv .github/workflows/macOS/Info.plist psxe.app/Contents/Info.plist
           mkdir -p psxe
           mv psxe.app psxe
           open psxe.app
    - uses: actions/upload-artifact@v3
      with:
        name: psxe
        path: psxe/
