name: macOS CI

on:
  push:
    branches: [ "actions" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: brew install sdl2
    - name: make
      run: make
    - name: Make executable
      run: chmod 755 bin/psxe
    - name: Test
      run: ls ~/Library/Frameworks
    - uses: actions/upload-artifact@v3
      with:
        name: binary
        path: bin/psxe