name: Windows CI

on:
  push:
    branches: [ "actions" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run build-deps
      run: ./build-deps.ps1
    - name: Build
      run: |
           ./build-win.ps1
           dir
    - uses: actions/upload-artifact@v3
      with:
        name: binary
        path: bin/psxe.exe